# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\cmd_hmi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CmdWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 442)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 681, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_cmd = QtWidgets.QPushButton(self.frame)
        self.pushButton_cmd.setGeometry(QtCore.QRect(350, 30, 93, 28))
        self.pushButton_cmd.setObjectName("pushButton_cmd")
        self.lineEdit_cmd = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_cmd.setGeometry(QtCore.QRect(10, 30, 331, 31))
        self.lineEdit_cmd.setObjectName("lineEdit_cmd")
        self.textEdit_log = QtWidgets.QTextEdit(self.frame)
        self.textEdit_log.setGeometry(QtCore.QRect(10, 90, 661, 331))
        self.textEdit_log.setObjectName("textEdit_log")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FastCharge EV command"))
        self.pushButton_cmd.setText(_translate("MainWindow", "Send"))
        self.label.setText(_translate("MainWindow", "Command"))
        self.label_2.setText(_translate("MainWindow", "Response"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_CmdWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
